# Generated by Django 4.2.16 on 2024-12-13 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='Desconocido', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='Desconocido', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='Desconocido', max_length=250)),
                ('apellido', models.CharField(default='Desconocido', max_length=250)),
                ('email', models.CharField(default='Desconocido', max_length=250)),
                ('telefono', models.CharField(default='Desconocido', max_length=250)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agencia.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fabricacion', models.CharField(default='Desconocido', max_length=250)),
                ('precio', models.CharField(default='Desconocido', max_length=250)),
                ('placa', models.CharField(default='Desconocido', max_length=250)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agencia.modelo')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agencia.propietario')),
            ],
        ),
    ]
